// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngduttspchloegdgqofp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZHV0dHNwY2hsb2VnZGdxb2ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODM0MzQsImV4cCI6MjA2NzQ1OTQzNH0.dVW9P2EdBzuDbQFC2i1WqymzI23wMxzp4tWlLxznBBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});